/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Business;
import model.Owner;
import model.Service;
import model.Vehicle;
import ui_VehicleService.RegisterOwnerVehicleJPanel;
import ui_VehicleService.ManageVehiclesJPanel;


/**
 *
 * @author wakingstardust
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private Business business;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.business = new Business();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnServices = new javax.swing.JButton();
        btnVehicleOwner = new javax.swing.JButton();
        btnManageVehicles = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnServices.setBackground(new java.awt.Color(153, 204, 255));
        btnServices.setText("Services");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnVehicleOwner.setBackground(new java.awt.Color(153, 204, 255));
        btnVehicleOwner.setText("Vehicle & Owner");
        btnVehicleOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleOwnerActionPerformed(evt);
            }
        });

        btnManageVehicles.setBackground(new java.awt.Color(153, 204, 255));
        btnManageVehicles.setText("Manage Vehicles");
        btnManageVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnServices)
                .addGap(18, 18, 18)
                .addComponent(btnVehicleOwner)
                .addGap(18, 18, 18)
                .addComponent(btnManageVehicles)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServices)
                    .addComponent(btnVehicleOwner)
                    .addComponent(btnManageVehicles))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
        
        CreateServiceJPanel panel = new CreateServiceJPanel(userProcessContainer, business);
        userProcessContainer.add("CreateServiceJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnVehicleOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleOwnerActionPerformed
        // TODO add your handling code here:
        
        RegisterOwnerVehicleJPanel panel = new RegisterOwnerVehicleJPanel(userProcessContainer, business);
        userProcessContainer.add("RegisterOwnerVehicleJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnVehicleOwnerActionPerformed

    private void btnManageVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehiclesActionPerformed
        // TODO add your handling code here:
        
        ManageVehiclesJPanel panel = new ManageVehiclesJPanel(userProcessContainer, business);
        userProcessContainer.add("ManageVehiclesJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnManageVehiclesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVehicles;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnVehicleOwner;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData(){
        
        Service newService = business.getServiceCatalog().addService();
        newService.setServiceName("Oil Change");
        newService.setDescription("Regular oil change");
        newService.setPrice(45.00);
        newService.setEstimatedTime(30);

        Service anotherService = business.getServiceCatalog().addService();
        anotherService.setServiceName("Car Wash");
        anotherService.setDescription("Full car wash");
        anotherService.setPrice(25.00);
        anotherService.setEstimatedTime(20);

        Service thirdService = business.getServiceCatalog().addService();
        thirdService.setServiceName("Puncture");
        thirdService.setDescription("Tire puncture repair");
        thirdService.setPrice(35.00);
        thirdService.setEstimatedTime(45);

        Owner owner1 = new Owner("John Smith", "123 Main St", "john@email.com", 5551234567L);
        Vehicle vehicle1 = business.getVehicleDirectory().addVehicle();
        vehicle1.setMake("Toyota");
        vehicle1.setModel("Camry");
        vehicle1.setYear(2020);
        vehicle1.setVin("VIN001");
        vehicle1.setMileage(35000);
        vehicle1.setOwner(owner1);
        vehicle1.addService(newService);

        Owner owner2 = new Owner("Jane Doe", "456 Oak Ave", "jane@email.com", 5559876543L);
        Vehicle vehicle2 = business.getVehicleDirectory().addVehicle();
        vehicle2.setMake("Toyota");
        vehicle2.setModel("Corolla");
        vehicle2.setYear(2021);
        vehicle2.setVin("VIN002");
        vehicle2.setMileage(22000);
        vehicle2.setOwner(owner2);
        vehicle2.addService(anotherService);

        Owner owner3 = new Owner("Bob Wilson", "789 Pine Rd", "bob@email.com", 5554567890L);
        Vehicle vehicle3 = business.getVehicleDirectory().addVehicle();
        vehicle3.setMake("Honda");
        vehicle3.setModel("Civic");
        vehicle3.setYear(2019);
        vehicle3.setVin("VIN003");
        vehicle3.setMileage(48000);
        vehicle3.setOwner(owner3);
        vehicle3.addService(thirdService);

        Owner owner4 = new Owner("Alice Brown", "321 Elm St", "alice@email.com", 5551112222L);
        Vehicle vehicle4 = business.getVehicleDirectory().addVehicle();
        vehicle4.setMake("Ford");
        vehicle4.setModel("Focus");
        vehicle4.setYear(2022);
        vehicle4.setVin("VIN004");
        vehicle4.setMileage(15000);
        vehicle4.setOwner(owner4);
        vehicle4.addService(newService);

        Owner owner5 = new Owner("Charlie Davis", "654 Maple Dr", "charlie@email.com", 5553334444L);
        Vehicle vehicle5 = business.getVehicleDirectory().addVehicle();
        vehicle5.setMake("Chevrolet");
        vehicle5.setModel("Malibu");
        vehicle5.setYear(2018);
        vehicle5.setVin("VIN005");
        vehicle5.setMileage(62000);
        vehicle5.setOwner(owner5);
        vehicle5.addService(anotherService);
        
    }



}
