/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import Business.Person.Person;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

import UserInterface.WorkAreas.AdminRole.AdminRoleWorkAreaJPanel;


/**
 *
 * @author wakingstardust
 */
public class ManageStudentsJPanel extends javax.swing.JPanel {
      
    Business business;
    JPanel CardSequencePanel;
    
    /**
     * Creates new form ManageStudentsJPanel
     */
    public ManageStudentsJPanel(Business b, JPanel clp) {
        
        initComponents();
        
        this.business = b;
        this.CardSequencePanel = clp;
        populateTable();

    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0); // Clear existing rows
        model.setColumnCount(0); // Clear columns
        
        // Define columns
        model.addColumn("Name");
        model.addColumn("NUID");
        
        // Get all students from directory
        ArrayList<StudentProfile> students = business.getStudentDirectory().getStudentList();
        
        // Add each student to table using standard for loop
        for(StudentProfile sp : students) {
            Person person = sp.getPerson();
            Object[] row = new Object[2];
            row[0] = person.getPersonId();
            row[1] = person.getNuid() != null ? person.getNuid() : "N/A";
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Manage Students");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "NUID"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAdd.setText("Add Student");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Student");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnRefresh)
                .addGap(43, 43, 43)
                .addComponent(btnAdd)
                .addGap(42, 42, 42)
                .addComponent(btnDelete)
                .addGap(53, 53, 53)
                .addComponent(btnBack)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
        populateTable();
        JOptionPane.showMessageDialog(this, "Student list refreshed");
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String name = JOptionPane.showInputDialog(this, "Enter Student Name:");
        if(name == null || name.isEmpty()) return;
        
        String nuid = JOptionPane.showInputDialog(this, "Enter NUID:");
        if(nuid == null || nuid.isEmpty()) return;
        
        String username = JOptionPane.showInputDialog(this, "Enter Username:");
        if(username == null || username.isEmpty()) return;
        
        String password = JOptionPane.showInputDialog(this, "Enter Password:");
        if(password == null || password.isEmpty()) return;
        
        Person existingPerson = business.getPersonDirectory().findPersonByNuid(nuid);
        if(existingPerson != null){
            JOptionPane.showMessageDialog(this, "NUID already exists", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Person newPerson = business.getPersonDirectory().newPerson(name);
        newPerson.setNuid(nuid);
        
        StudentProfile newStudent = business.getStudentDirectory().newStudentProfile(newPerson);
        
        business.getUserAccountDirectory().newUserAccount(newStudent, username, password);
        
        JOptionPane.showMessageDialog(this, "Student added successfully");
        populateTable();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblStudents.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Please select a student to delete", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this student?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION);
        if(confirm != JOptionPane.YES_OPTION) return;

        // Get student name from selected row
        String studentName = (String) tblStudents.getValueAt(selectedRow, 0);

        // Remove from directory
        business.getStudentDirectory().removeStudent(studentName);

        JOptionPane.showMessageDialog(this, "Student deleted successfully");
        populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        AdminRoleWorkAreaJPanel adminPanel = new AdminRoleWorkAreaJPanel(business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("admin", adminPanel);
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
