/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui_VehicleService;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business;
import model.Owner;
import model.Service;
import model.Vehicle;

/**
 *
 * @author wakingstardust
 */
public class RegisterOwnerVehicleJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    
    /**
     * Creates new form RegisterOwnerVehicleJPanel
     */
    public RegisterOwnerVehicleJPanel(JPanel container, Business business) {
        initComponents();
        
        this.userProcessContainer = container;
        this.business = business;
        
        populateServiceComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOwnerLastName = new javax.swing.JLabel();
        lblMechanicName = new javax.swing.JLabel();
        lblOwnerId = new javax.swing.JLabel();
        txtOwnerId = new javax.swing.JTextField();
        txtOwnerFirstName = new javax.swing.JTextField();
        txtOwnerLastName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtServiceDate = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblOwnerTitle = new javax.swing.JLabel();
        lblOwnerFirstName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtModel = new javax.swing.JTextField();
        txtRegistration = new javax.swing.JTextField();
        lblVehicleTitle = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblRegistration = new javax.swing.JLabel();
        lblServiceOpted = new javax.swing.JLabel();
        lblVehicleId = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        cmbService = new javax.swing.JComboBox<>();

        lblOwnerLastName.setText("Owner Last Name");

        lblMechanicName.setText("Service Date");

        lblOwnerId.setText("Owner ID");

        btnRegister.setText("Register Service");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txtServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceDateActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOwnerTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblOwnerTitle.setText("Owner Details");

        lblOwnerFirstName.setText("Owner First Name");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrationActionPerformed(evt);
            }
        });

        lblVehicleTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblVehicleTitle.setText("Vehicle Details");

        lblModel.setText("Model");

        lblMake.setText("Make");

        lblRegistration.setText("Registration Number");

        lblServiceOpted.setText("Service Opted");

        lblVehicleId.setText("Vehicle ID");

        cmbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMake)
                            .addComponent(lblRegistration)
                            .addComponent(lblModel)
                            .addComponent(lblServiceOpted)
                            .addComponent(lblVehicleId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVehicleId)
                            .addComponent(txtMake)
                            .addComponent(txtModel)
                            .addComponent(txtRegistration)
                            .addComponent(cmbService, 0, 156, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVehicleTitle)
                        .addGap(137, 137, 137))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblVehicleTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistration))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceOpted)
                    .addComponent(cmbService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOwnerFirstName)
                                    .addComponent(lblMechanicName)
                                    .addComponent(lblOwnerLastName)
                                    .addComponent(lblOwnerId))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOwnerId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOwnerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOwnerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(lblOwnerTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btnRegister)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblOwnerTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOwnerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOwnerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOwnerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMechanicName))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:

        String ownerId = txtOwnerId.getText();
        String ownerFirstName = txtOwnerFirstName.getText();
        String ownerLastName = txtOwnerLastName.getText();
        String serviceDate = txtServiceDate.getText();
        
        String vehicleId = txtVehicleId.getText();
        String make = txtMake.getText();
        String model = txtModel.getText();
        String registration = txtRegistration.getText();
        
        if (ownerId.isBlank() || ownerFirstName.isBlank() || ownerLastName.isBlank() || serviceDate.isBlank() ||
            vehicleId.isBlank() || make.isBlank() || model.isBlank() || registration.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cmbService.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a service.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String ownerName = ownerFirstName + " " + ownerLastName;
        Owner newOwner = new Owner(ownerName, "", "", 0L);
        
        Vehicle newVehicle = business.getVehicleDirectory().addVehicle();
        newVehicle.setVin(vehicleId);
        newVehicle.setMake(make);
        newVehicle.setModel(model);
        newVehicle.setYear(2024);
        newVehicle.setMileage(0);
        newVehicle.setOwner(newOwner);
        
        String selectedServiceName = (String) cmbService.getSelectedItem();
        Service selectedService = business.getServiceCatalog().searchService(selectedServiceName);
        newVehicle.addService(selectedService);
        
        JOptionPane.showMessageDialog(this, "Vehicle registered successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        txtOwnerId.setText("");
        txtOwnerFirstName.setText("");
        txtOwnerLastName.setText("");
        txtServiceDate.setText("");
        txtVehicleId.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtRegistration.setText("");
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceDateActionPerformed

    private void txtRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrationActionPerformed

    private void cmbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbService;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblMechanicName;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerFirstName;
    private javax.swing.JLabel lblOwnerId;
    private javax.swing.JLabel lblOwnerLastName;
    private javax.swing.JLabel lblOwnerTitle;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblServiceOpted;
    private javax.swing.JLabel lblVehicleId;
    private javax.swing.JLabel lblVehicleTitle;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerFirstName;
    private javax.swing.JTextField txtOwnerId;
    private javax.swing.JTextField txtOwnerLastName;
    private javax.swing.JTextField txtRegistration;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtVehicleId;
    // End of variables declaration//GEN-END:variables

    private void populateServiceComboBox() {
        cmbService.removeAllItems();
        for (Service s : business.getServiceCatalog().getServices()) {
            cmbService.addItem(s.getServiceName());
        }
    }
}
