/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author wakingstardust
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person; 
    public CreatePersonJPanel(Person p) {
        initComponents();
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblMiddleInitial = new javax.swing.JLabel();
        fieldMiddleInitial = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lblMaritalStatus = new javax.swing.JLabel();
        fieldMaritalStatus = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Create Person");

        lblFirstName.setText("First Name");

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name");

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        lblMiddleInitial.setText("Middle Inital");

        fieldMiddleInitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMiddleInitialActionPerformed(evt);
            }
        });

        lblAge.setText("Age");

        fieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAgeActionPerformed(evt);
            }
        });

        lblMaritalStatus.setText("Marital Status (Yes or No)");

        fieldMaritalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMaritalStatusActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLastName)
                                .addComponent(lblFirstName)
                                .addComponent(lblMaritalStatus))
                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMiddleInitial, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(fieldMaritalStatus)
                            .addComponent(fieldMiddleInitial)
                            .addComponent(fieldAge)
                            .addComponent(fieldLastName))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btnSave)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMiddleInitial)
                    .addComponent(fieldMiddleInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaritalStatus)
                    .addComponent(fieldMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(btnSave)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgeActionPerformed

    private void fieldMiddleInitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMiddleInitialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMiddleInitialActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // Step 1: collect text from the field
        String firstName = fieldFirstName.getText();
        String middleInitial = fieldMiddleInitial.getText();
        String lastName = fieldLastName.getText();
        String age = fieldAge.getText();
        String maritalStatus = fieldMaritalStatus.getText();

        // Check if any field is empty
        if (firstName.isEmpty() || middleInitial.isEmpty() || lastName.isEmpty() || age.isEmpty() || maritalStatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out!");
            return;
        }
        
        // Validate middle initial is only one character
        if (middleInitial.length() != 1) {
            JOptionPane.showMessageDialog(this, "Middle Initial must be exactly one character!");
            return;
        }
        
        // Validate age is a number
        try {
            Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a valid number!");
            return;
        }
        
        // Validate marital status is yes or no
        if (!maritalStatus.equals("yes") && !maritalStatus.equals("no")) {
            JOptionPane.showMessageDialog(this, "Marital Status must be 'Yes' or 'No'!");
            return;
        }

        // Step 2: put those infomation to person
        person.setFirstName(firstName);
        person.setMiddleInitial(middleInitial.charAt(0));
        person.setLastName(lastName);
        person.setAge(Integer.parseInt(age));
        person.setMaritalStatus(maritalStatus.equals("yes"));
        
        //Step 3: pop up message appears
        JOptionPane.showMessageDialog(this, "Sucessfully Saved!");
        
        //Step 4: clear all fields
        fieldFirstName.setText("");
        fieldMiddleInitial.setText("");
        fieldLastName.setText("");
        fieldAge.setText("");
        fieldMaritalStatus.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fieldMaritalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMaritalStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMaritalStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldMaritalStatus;
    private javax.swing.JTextField fieldMiddleInitial;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblMiddleInitial;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
