/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author wakingstardust
 */
public class CreateBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person; 
    public CreateBankAccountJPanel(Person p) {
        initComponents();
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBankNickname = new javax.swing.JLabel();
        fieldBankNickname = new javax.swing.JTextField();
        lblBankAccountType = new javax.swing.JLabel();
        fieldBankAccountType = new javax.swing.JTextField();
        lblAccountNumber = new javax.swing.JLabel();
        fieldBankAccountNumber = new javax.swing.JTextField();
        lblBankRoutingNumber = new javax.swing.JLabel();
        fieldBankRoutingNumber = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        fieldBankName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Create Bank Account");

        lblBankNickname.setText("Bank Account Nickname");

        fieldBankNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankNicknameActionPerformed(evt);
            }
        });

        lblBankAccountType.setText("Bank Account Type (Checking or Saving)");

        fieldBankAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankAccountTypeActionPerformed(evt);
            }
        });

        lblAccountNumber.setText("Account Number");

        fieldBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankAccountNumberActionPerformed(evt);
            }
        });

        lblBankRoutingNumber.setText("Routing Number");

        fieldBankRoutingNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankRoutingNumberActionPerformed(evt);
            }
        });

        lblBankName.setText("Bank Name");

        fieldBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankNameActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBankAccountType)
                            .addComponent(lblBankNickname)
                            .addComponent(lblAccountNumber)
                            .addComponent(lblBankRoutingNumber)
                            .addComponent(lblBankName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldBankRoutingNumber)
                            .addComponent(fieldBankAccountNumber)
                            .addComponent(fieldBankNickname)
                            .addComponent(fieldBankAccountType)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankNickname)
                    .addComponent(fieldBankNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountType)
                    .addComponent(fieldBankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber)
                    .addComponent(fieldBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankRoutingNumber)
                    .addComponent(fieldBankRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnSave)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBalanceActionPerformed

    private void fieldAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAccountTypeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        // Step 1: collect text from the field
        String nickname = fieldBankNickname.getText();
        String accountNumber = fieldBankAccountNumber.getText();
        String routingNumber = fieldBankRoutingNumber.getText();
        String accountType = fieldBankAccountType.getText();
        String bankName = fieldBankName.getText();

        // Step 2: put those infomation to person bank account
        person.getBankAccount().setNickname(nickname);
        person.getBankAccount().setAccountNumber(accountNumber);
        person.getBankAccount().setRoutingNumber(routingNumber);
        person.getBankAccount().setAccountType(accountType);
        person.getBankAccount().setBankName(bankName);

        //Step 3: pop up message appears
        JOptionPane.showMessageDialog(this, "Sucessfully Saved!");

        //Step 4: clear all fields
        fieldBankNickname.setText("");
        fieldBankAccountNumber.setText("");
        fieldBankRoutingNumber.setText("");
        fieldBankAccountType.setText("");
        fieldBankName.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fieldAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAccountNumberActionPerformed

    private void fieldBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankNameActionPerformed

    private void fieldRoutingNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRoutingNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRoutingNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldBankAccountNumber;
    private javax.swing.JTextField fieldBankAccountType;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBankNickname;
    private javax.swing.JTextField fieldBankRoutingNumber;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBankAccountType;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankNickname;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
