/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author wakingstardust
 */
public class CreateLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person; 
    public CreateLocalAddressJPanel(Person p) {
        initComponents();
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblLocalAddressLine1 = new javax.swing.JLabel();
        fieldLocalAddressLine1 = new javax.swing.JTextField();
        lblLocalAddressLine2 = new javax.swing.JLabel();
        fieldLocalAddressLine2 = new javax.swing.JTextField();
        lblLocalCity = new javax.swing.JLabel();
        fieldLocalCity = new javax.swing.JTextField();
        lblLocalState = new javax.swing.JLabel();
        fieldLocalState = new javax.swing.JTextField();
        fieldLocalZipCode = new javax.swing.JTextField();
        lblLocalZipCode = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Create Local Address");

        lblLocalAddressLine1.setText("Address Line 1");

        fieldLocalAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalAddressLine1ActionPerformed(evt);
            }
        });

        lblLocalAddressLine2.setText("Address Line 2");

        fieldLocalAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalAddressLine2ActionPerformed(evt);
            }
        });

        lblLocalCity.setText("City");

        fieldLocalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalCityActionPerformed(evt);
            }
        });

        lblLocalState.setText("State (CA)");

        fieldLocalState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalStateActionPerformed(evt);
            }
        });

        fieldLocalZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalZipCodeActionPerformed(evt);
            }
        });

        lblLocalZipCode.setText("Zip Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLocalAddressLine2)
                                    .addComponent(lblLocalAddressLine1)
                                    .addComponent(lblLocalCity)
                                    .addComponent(lblLocalState)
                                    .addComponent(lblLocalZipCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldLocalState)
                                    .addComponent(fieldLocalCity)
                                    .addComponent(fieldLocalAddressLine1)
                                    .addComponent(fieldLocalAddressLine2)
                                    .addComponent(fieldLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblTitle)))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalAddressLine1)
                    .addComponent(fieldLocalAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalAddressLine2)
                    .addComponent(fieldLocalAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalCity)
                    .addComponent(fieldLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalState)
                    .addComponent(fieldLocalState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalZipCode)
                    .addComponent(fieldLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnSave)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCityActionPerformed

    private void fieldStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        // Step 1: collect text from the field
        String addressLine1 = fieldLocalAddressLine1.getText();
        String addressLine2 = fieldLocalAddressLine2.getText();
        String city = fieldLocalCity.getText();
        String state = fieldLocalState.getText();
        String zipCode = fieldLocalZipCode.getText();

        // Check if any field is empty
        if (addressLine1.isEmpty() || addressLine2.isEmpty() || city.isEmpty() || state.isEmpty() || zipCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out!");
            return;
        }
        
         // Make sure the zip code is valid
        try {
            Integer.parseInt(zipCode);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Zip Code must be a valid number!");
            return;
        }

        // Step 2: put the infomation to person local address
        person.getLocalAddress().setAddressLine1(addressLine1);
        person.getLocalAddress().setAddressLine2(addressLine2);
        person.getLocalAddress().setCity(city);
        person.getLocalAddress().setState(state);
        person.getLocalAddress().setZipCode(zipCode);

        //Step 3: pop up message appears
        JOptionPane.showMessageDialog(this, "Sucessfully Saved!");

        //Step 4: clear all fields
        fieldLocalAddressLine1.setText("");
        fieldLocalAddressLine2.setText("");
        fieldLocalCity.setText("");
        fieldLocalState.setText("");
        fieldLocalZipCode.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fieldStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetNameActionPerformed

    private void fieldZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldZipCodeActionPerformed

    private void fieldUnitNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUnitNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUnitNumActionPerformed

    private void fieldLocalStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalStateActionPerformed

    private void fieldLocalZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalZipCodeActionPerformed

    private void fieldLocalAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalAddressLine1ActionPerformed

    private void fieldLocalAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalAddressLine2ActionPerformed

    private void fieldLocalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldLocalAddressLine1;
    private javax.swing.JTextField fieldLocalAddressLine2;
    private javax.swing.JTextField fieldLocalCity;
    private javax.swing.JTextField fieldLocalState;
    private javax.swing.JTextField fieldLocalZipCode;
    private javax.swing.JLabel lblLocalAddressLine1;
    private javax.swing.JLabel lblLocalAddressLine2;
    private javax.swing.JLabel lblLocalCity;
    private javax.swing.JLabel lblLocalState;
    private javax.swing.JLabel lblLocalZipCode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
