/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;

/**
 *
 * @author wakingstardust
 */
public class ViewBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewBankAccountJPanel(Person p) {
        initComponents();
        person = p;
        display();

    }
    
    
    private void display() {
        fieldName.setText(product.getName());
        fieldName.setText(product.getName());
        fieldDescription.setText(product.getDescription());
        fieldAvailability.setText(product.getAvailNum());
        fieldPrice.setText(product.getPrice());
        fieldManuStreet.setText(product.getManufactureAddress().getStreetName());
        fieldManuUnit.setText(product.getManufactureAddress().getUnitNum());
        fieldManuCity.setText(product.getManufactureAddress().getCity());
        fieldManuZipCode.setText(product.getManufactureAddress().getZipCode());
        fieldShippingStreet.setText(product.getShippingAddress().getStreetName());
        fieldShippingUnit.setText(product.getShippingAddress().getUnitNum());
        fieldShippingCity.setText(product.getShippingAddress().getCity());
        fieldShippingZipCode.setText(product.getShippingAddress().getZipCode());
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBankName = new javax.swing.JLabel();
        fieldBankName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblBankNickname = new javax.swing.JLabel();
        fieldBankNickname = new javax.swing.JTextField();
        lblBankAccountType = new javax.swing.JLabel();
        fieldBankAccountType = new javax.swing.JTextField();
        lblAccountNumber = new javax.swing.JLabel();
        fieldBankAccountNumber = new javax.swing.JTextField();
        lblBankRoutingNumber = new javax.swing.JLabel();
        fieldBankRoutingNumber = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        lblBankName.setText("Bank Name");

        fieldBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankNameActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("View Bank Account");

        lblBankNickname.setText("Bank Account Nickname");

        fieldBankNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankNicknameActionPerformed(evt);
            }
        });

        lblBankAccountType.setText("Bank Account Type (Checking or Saving)");

        fieldBankAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankAccountTypeActionPerformed(evt);
            }
        });

        lblAccountNumber.setText("Account Number");

        fieldBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankAccountNumberActionPerformed(evt);
            }
        });

        lblBankRoutingNumber.setText("Routing Number");

        fieldBankRoutingNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankRoutingNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBankAccountType)
                            .addComponent(lblBankNickname)
                            .addComponent(lblAccountNumber)
                            .addComponent(lblBankRoutingNumber)
                            .addComponent(lblBankName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldBankRoutingNumber)
                            .addComponent(fieldBankAccountNumber)
                            .addComponent(fieldBankNickname)
                            .addComponent(fieldBankAccountType)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankNickname)
                    .addComponent(fieldBankNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountType)
                    .addComponent(fieldBankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber)
                    .addComponent(fieldBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankRoutingNumber)
                    .addComponent(fieldBankRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankNameActionPerformed

    private void fieldBankNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankNicknameActionPerformed

    private void fieldBankAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankAccountTypeActionPerformed

    private void fieldBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankAccountNumberActionPerformed

    private void fieldBankRoutingNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankRoutingNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankRoutingNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldBankAccountNumber;
    private javax.swing.JTextField fieldBankAccountType;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBankNickname;
    private javax.swing.JTextField fieldBankRoutingNumber;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBankAccountType;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankNickname;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
