/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;

/**
 *
 * @author wakingstardust
 */
public class ViewLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewLocalAddressJPanel(Person p) {
        initComponents();
        person = p;
        display();

    }
    
    
    private void display() {
        fieldName.setText(product.getName());
        fieldName.setText(product.getName());
        fieldDescription.setText(product.getDescription());
        fieldAvailability.setText(product.getAvailNum());
        fieldPrice.setText(product.getPrice());
        fieldManuStreet.setText(product.getManufactureAddress().getStreetName());
        fieldManuUnit.setText(product.getManufactureAddress().getUnitNum());
        fieldManuCity.setText(product.getManufactureAddress().getCity());
        fieldManuZipCode.setText(product.getManufactureAddress().getZipCode());
        fieldShippingStreet.setText(product.getShippingAddress().getStreetName());
        fieldShippingUnit.setText(product.getShippingAddress().getUnitNum());
        fieldShippingCity.setText(product.getShippingAddress().getCity());
        fieldShippingZipCode.setText(product.getShippingAddress().getZipCode());
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldLocalAddressLine1 = new javax.swing.JTextField();
        lblLocalAddressLine2 = new javax.swing.JLabel();
        fieldLocalAddressLine2 = new javax.swing.JTextField();
        lblLocalCity = new javax.swing.JLabel();
        fieldLocalCity = new javax.swing.JTextField();
        lblLocalState = new javax.swing.JLabel();
        fieldLocalState = new javax.swing.JTextField();
        fieldLocalZipCode = new javax.swing.JTextField();
        lblLocalZipCode = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblLocalAddressLine1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        fieldLocalAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalAddressLine1ActionPerformed(evt);
            }
        });

        lblLocalAddressLine2.setText("Address Line 2");

        fieldLocalAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalAddressLine2ActionPerformed(evt);
            }
        });

        lblLocalCity.setText("City");

        fieldLocalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalCityActionPerformed(evt);
            }
        });

        lblLocalState.setText("State (CA)");

        fieldLocalState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalStateActionPerformed(evt);
            }
        });

        fieldLocalZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalZipCodeActionPerformed(evt);
            }
        });

        lblLocalZipCode.setText("Zip Code");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("View Local Address");

        lblLocalAddressLine1.setText("Address Line 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(154, 154, 154))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLocalAddressLine2)
                        .addComponent(lblLocalAddressLine1)
                        .addComponent(lblLocalCity)
                        .addComponent(lblLocalState)
                        .addComponent(lblLocalZipCode))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldLocalState)
                        .addComponent(fieldLocalCity)
                        .addComponent(fieldLocalAddressLine1)
                        .addComponent(fieldLocalAddressLine2)
                        .addComponent(fieldLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(144, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lblTitle)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocalAddressLine1)
                        .addComponent(fieldLocalAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocalAddressLine2)
                        .addComponent(fieldLocalAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocalCity)
                        .addComponent(fieldLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocalState)
                        .addComponent(fieldLocalState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocalZipCode)
                        .addComponent(fieldLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLocalAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalAddressLine1ActionPerformed

    private void fieldLocalAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalAddressLine2ActionPerformed

    private void fieldLocalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalCityActionPerformed

    private void fieldLocalStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalStateActionPerformed

    private void fieldLocalZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalZipCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldLocalAddressLine1;
    private javax.swing.JTextField fieldLocalAddressLine2;
    private javax.swing.JTextField fieldLocalCity;
    private javax.swing.JTextField fieldLocalState;
    private javax.swing.JTextField fieldLocalZipCode;
    private javax.swing.JLabel lblLocalAddressLine1;
    private javax.swing.JLabel lblLocalAddressLine2;
    private javax.swing.JLabel lblLocalCity;
    private javax.swing.JLabel lblLocalState;
    private javax.swing.JLabel lblLocalZipCode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
