/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;

/**
 *
 * @author wakingstardust
 */
public class ViewHomeAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewHomeAddressJPanel(Person p) {
        initComponents();
        person = p;
        display();

    }
    
    
    private void display() {
        fieldHomeAddressLine1.setText(person.getHomeAddress().getStreetName());
        fieldHomeAddressLine2.setText(person.getHomeAddress().getUnitNum());
        fieldHomeCity.setText(person.getHomeAddress().getCity());
        fieldHomeState.setText(person.getHomeAddress().getState());
        fieldHomeZipCode.setText(person.getHomeAddress().getZipCode());
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblHomeAddressLine1 = new javax.swing.JLabel();
        fieldHomeAddressLine1 = new javax.swing.JTextField();
        lblHomeAddressLine2 = new javax.swing.JLabel();
        fieldHomeAddressLine2 = new javax.swing.JTextField();
        lblHomeState = new javax.swing.JLabel();
        fieldHomeState = new javax.swing.JTextField();
        lblHomeZipCode = new javax.swing.JLabel();
        fieldHomeZipCode = new javax.swing.JTextField();
        lblHomeCity = new javax.swing.JLabel();
        fieldHomeCity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("View Home Address");

        lblHomeAddressLine1.setText("Address Line 1");

        fieldHomeAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomeAddressLine1ActionPerformed(evt);
            }
        });

        lblHomeAddressLine2.setText("Address Line 2");

        fieldHomeAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomeAddressLine2ActionPerformed(evt);
            }
        });

        lblHomeState.setText("State (CA)");

        fieldHomeState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomeStateActionPerformed(evt);
            }
        });

        lblHomeZipCode.setText("Zip Code");

        fieldHomeZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomeZipCodeActionPerformed(evt);
            }
        });

        lblHomeCity.setText("City");

        fieldHomeCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomeCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHomeAddressLine2)
                            .addComponent(lblHomeAddressLine1)
                            .addComponent(lblHomeCity)
                            .addComponent(lblHomeState)
                            .addComponent(lblHomeZipCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldHomeState)
                            .addComponent(fieldHomeCity)
                            .addComponent(fieldHomeAddressLine1)
                            .addComponent(fieldHomeAddressLine2)
                            .addComponent(fieldHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitle))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddressLine1)
                    .addComponent(fieldHomeAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddressLine2)
                    .addComponent(fieldHomeAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeCity)
                    .addComponent(fieldHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeState)
                    .addComponent(fieldHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeZipCode)
                    .addComponent(fieldHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHomeStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomeStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomeStateActionPerformed

    private void fieldHomeZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomeZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomeZipCodeActionPerformed

    private void fieldHomeAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomeAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomeAddressLine1ActionPerformed

    private void fieldHomeAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomeAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomeAddressLine2ActionPerformed

    private void fieldHomeCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomeCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomeCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldHomeAddressLine1;
    private javax.swing.JTextField fieldHomeAddressLine2;
    private javax.swing.JTextField fieldHomeCity;
    private javax.swing.JTextField fieldHomeState;
    private javax.swing.JTextField fieldHomeZipCode;
    private javax.swing.JLabel lblHomeAddressLine1;
    private javax.swing.JLabel lblHomeAddressLine2;
    private javax.swing.JLabel lblHomeCity;
    private javax.swing.JLabel lblHomeState;
    private javax.swing.JLabel lblHomeZipCode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
